version: 2.1

workflows:
  test-env-workflow:
    jobs:
      - print_hello
      - print_world:
          requires: print_hello
      - print_appname

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_appname:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env file that is part of our project"
          command: |
            echo $APP_NAME
